{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1a06bd1-03c3-4deb-8636-84764b75ef78",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "yfinance_data.py\n",
    "\n",
    "Módulo para buscar dados de um ticker via yfinance e gerar gráficos em PNG.\n",
    "\n",
    "Funções principais:\n",
    "- get_yf_data(mainticker, period, interval)\n",
    "    -> df_history, info, recs_summary\n",
    "- save_yf_charts(df_history, mainticker, out_dir)\n",
    "    -> dict com paths dos ficheiros PNG\n",
    "- get_yf_package(mainticker, period, interval, charts_dir)\n",
    "    -> dicionário com tudo (dados + paths dos gráficos)\n",
    "\"\"\"\n",
    "\n",
    "from pathlib import Path\n",
    "from typing import Dict, Any, Tuple, Optional\n",
    "\n",
    "import yfinance as yf\n",
    "import matplotlib\n",
    "matplotlib.use(\"Agg\")  # backend sem janela gráfica (bom para servidores / scripts)\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "def get_yf_data(\n",
    "    mainticker: str,\n",
    "    period: str = \"5y\",\n",
    "    interval: str = \"1d\",\n",
    ") -> Tuple[pd.DataFrame, Dict[str, Any], Optional[pd.DataFrame]]:\n",
    "    \"\"\"\n",
    "    Faz o download dos dados do yfinance para um ticker.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    mainticker : str\n",
    "        Símbolo do ticker (ex: \"AAPL\", \"MSFT\").\n",
    "    period : str, opcional\n",
    "        Período do histórico (ex: \"1y\", \"5y\", \"max\").\n",
    "    interval : str, opcional\n",
    "        Intervalo do histórico (ex: \"1d\", \"1wk\", \"1mo\").\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    df_history : pd.DataFrame\n",
    "        Histórico de preços com colunas típicas (Open, High, Low, Close, Volume...).\n",
    "    info : dict\n",
    "        Dicionário com as informações do ticker (empresa, setor, etc.).\n",
    "    recs_summary : pd.DataFrame ou None\n",
    "        Resultado de tk.get_recommendations_summary(), se existir; caso contrário, None.\n",
    "    \"\"\"\n",
    "    tk = yf.Ticker(mainticker)\n",
    "\n",
    "    # Histórico de preços\n",
    "    df_history = tk.history(period=period, interval=interval)\n",
    "\n",
    "    # Info da empresa\n",
    "    info = tk.info  # normalmente é um dict grande\n",
    "\n",
    "    # Resumo de recomendações (nem todas as versões têm este método)\n",
    "    recs_summary = None\n",
    "    try:\n",
    "        if hasattr(tk, \"get_recommendations_summary\"):\n",
    "            recs_summary = tk.get_recommendations_summary()\n",
    "        elif hasattr(tk, \"recommendations_summary\"):\n",
    "            # fallback se for atributo em vez de método\n",
    "            recs_summary = tk.recommendations_summary\n",
    "    except Exception as e:\n",
    "        # Se der erro, simplesmente deixamos como None\n",
    "        print(f\"[WARN] Não foi possível obter recommendations_summary para {mainticker}: {e}\")\n",
    "\n",
    "    return df_history, info, recs_summary\n",
    "\n",
    "\n",
    "def save_yf_charts(\n",
    "    df_history: pd.DataFrame,\n",
    "    mainticker: str,\n",
    "    out_dir: str = \"charts\",\n",
    ") -> Dict[str, Path]:\n",
    "    \"\"\"\n",
    "    Cria e guarda gráficos em ficheiros PNG para um dado df_history.\n",
    "\n",
    "    Gráficos criados:\n",
    "    - price: evolução do preço de fecho\n",
    "    - volume: barras de volume\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    df_history : pd.DataFrame\n",
    "        DataFrame com histórico de preços (resultado de get_yf_data()).\n",
    "    mainticker : str\n",
    "        Símbolo do ticker, usado nos títulos e nomes dos ficheiros.\n",
    "    out_dir : str, opcional\n",
    "        Diretório onde os PNG serão guardados.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    chart_paths : dict\n",
    "        Dicionário com os paths dos ficheiros PNG, por exemplo:\n",
    "        {\n",
    "            \"price\": Path(\"charts/AAPL_price.png\"),\n",
    "            \"volume\": Path(\"charts/AAPL_volume.png\")\n",
    "        }\n",
    "    \"\"\"\n",
    "    out_path = Path(out_dir)\n",
    "    out_path.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "    chart_paths: Dict[str, Path] = {}\n",
    "\n",
    "    # --- Gráfico de preço de fecho ---\n",
    "    if \"Close\" in df_history.columns:\n",
    "        price_png = out_path / f\"{mainticker}_price.png\"\n",
    "\n",
    "        fig_price, ax_price = plt.subplots()\n",
    "        ax_price.plot(df_history.index, df_history[\"Close\"])\n",
    "        ax_price.set_title(f\"{mainticker} - Closing Price\")\n",
    "        ax_price.set_xlabel(\"Date\")\n",
    "        ax_price.set_ylabel(\"Price\")\n",
    "\n",
    "        fig_price.tight_layout()\n",
    "        fig_price.savefig(price_png, bbox_inches=\"tight\")\n",
    "        plt.close(fig_price)\n",
    "\n",
    "        chart_paths[\"price\"] = price_png\n",
    "    else:\n",
    "        print(f\"[WARN] df_history não tem coluna 'Close' para {mainticker}, não foi gerado gráfico de preço.\")\n",
    "\n",
    "    # --- Gráfico de volume ---\n",
    "    if \"Volume\" in df_history.columns:\n",
    "        volume_png = out_path / f\"{mainticker}_volume.png\"\n",
    "\n",
    "        fig_vol, ax_vol = plt.subplots()\n",
    "        ax_vol.bar(df_history.index, df_history[\"Volume\"])\n",
    "        ax_vol.set_title(f\"{mainticker} - Volume\")\n",
    "        ax_vol.set_xlabel(\"Date\")\n",
    "        ax_vol.set_ylabel(\"Volume\")\n",
    "\n",
    "        fig_vol.tight_layout()\n",
    "        fig_vol.savefig(volume_png, bbox_inches=\"tight\")\n",
    "        plt.close(fig_vol)\n",
    "\n",
    "        chart_paths[\"volume\"] = volume_png\n",
    "    else:\n",
    "        print(f\"[WARN] df_history não tem coluna 'Volume' para {mainticker}, não foi gerado gráfico de volume.\")\n",
    "\n",
    "    return chart_paths\n",
    "\n",
    "\n",
    "def get_yf_package(\n",
    "    mainticker: str,\n",
    "    period: str = \"5y\",\n",
    "    interval: str = \"1d\",\n",
    "    charts_dir: str = \"charts\",\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Função \"all-in-one\" para integrar no teu pipeline.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    mainticker : str\n",
    "        Símbolo do ticker (ex: \"AAPL\").\n",
    "    period : str, opcional\n",
    "        Período do histórico.\n",
    "    interval : str, opcional\n",
    "        Intervalo do histórico.\n",
    "    charts_dir : str, opcional\n",
    "        Diretório onde os gráficos serão guardados.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    result : dict\n",
    "        {\n",
    "            \"ticker\": mainticker,\n",
    "            \"history\": df_history,\n",
    "            \"info\": info,\n",
    "            \"recs_summary\": recs_summary,\n",
    "            \"charts\": {\n",
    "                \"price\": Path(...),\n",
    "                \"volume\": Path(...)\n",
    "            }\n",
    "        }\n",
    "    \"\"\"\n",
    "    df_history, info, recs_summary = get_yf_data(\n",
    "        mainticker=mainticker,\n",
    "        period=period,\n",
    "        interval=interval,\n",
    "    )\n",
    "\n",
    "    chart_paths = save_yf_charts(\n",
    "        df_history=df_history,\n",
    "        mainticker=mainticker,\n",
    "        out_dir=charts_dir,\n",
    "    )\n",
    "\n",
    "    result: Dict[str, Any] = {\n",
    "        \"ticker\": mainticker,\n",
    "        \"history\": df_history,\n",
    "        \"info\": info,\n",
    "        \"recs_summary\": recs_summary,\n",
    "        \"charts\": chart_paths,\n",
    "    }\n",
    "    return result\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Pequeno teste rápido se correres o ficheiro diretamente:\n",
    "    test_ticker = \"AAPL\"\n",
    "    print(f\"Teste rápido com {test_ticker}...\")\n",
    "    pkg = get_yf_package(test_ticker, period=\"1y\", interval=\"1d\", charts_dir=\"charts_test\")\n",
    "    print(\"Histórico:\", pkg[\"history\"].tail(3))\n",
    "    print(\"Info keys:\", list(pkg[\"info\"].keys())[:10])\n",
    "    print(\"Recs summary:\", pkg[\"recs_summary\"])\n",
    "    print(\"Charts:\", pkg[\"charts\"])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
